### ISSUE TITLE
[Fix Suggestions] Duplicate Node Check 

### ISSUE THREAD

**Issue by ylinzhi** [osmlab/atlas-checks#388]
**Which Atlas check is the fix suggestion related to?** 

Duplicate Node Check 
Description: [The purpose of this check is to identify Nodes that are in the exact same location](https://github.com/osmlab/atlas-checks/blob/fb2dd356ddd327c92fcea1f657f45cbdae6ddd5e/docs/checks/duplicateNodeCheck.md)
Script: https://github.com/osmlab/atlas-checks/blob/1a7dc0d816021e7cfb751ede47445e9e1c6d1186/src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicateNodeCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type of fixing: Geometry fix

- Operation: Delete

- Suggested Action: Remove duplicated node(s)

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by seancoulter** [comment]
👍

**Comment by reichg** [comment]
This check is only analyzing the location of the nodes that may be in the same spot but does not take any attributes into account. If we want a fix suggestion for removing duplicate nodes then the nodes should only be removed if they have the same attributes as the node that will be kept. The scenario where there are nodes in the same spot but with different tags could belong to a different flag that has instructions to investigate the nodes because they shouldn't be modeled on top of each other?  How does this sound and am I thinking about this in the right way? @sayas01 @Bentleysb

**Comment by atiannicelli** [comment]
Yes, I would think that you would only suggest to remove a node if it is exactly the same as another node (including tags). Also, I would only suggest to remove a node if that node is not referenced by any ways. For instance, if a mapper created an exact duplicate way with duplicated nodes I would not suggest to remove those node in this check, I would let the duplicate way check flag that issue.

If, however the two nodes (in the same place) have different tags then there may be reasons to merge the tags. (eg. a crosswalk node on top of a non tagged node of a way) This may be what you are suggesting would be a new check?

I'm actually not quite sure how this check can work very well since the default atlas generation process filters out all nodes that don't have tags so all the possible duplicate nodes with no tags will not be in the atlas files that we are scanning (unless we use the "keepAll" flag.

**Comment by reichg** [comment]
>Yes, I would think that you would only suggest to remove a node if it is exactly the same as another node (including tags). Also, I would only suggest to remove a node if that node is not referenced by any ways. For instance, if a mapper created an exact duplicate way with duplicated nodes I would not suggest to remove those node in this check, I would let the duplicate way check flag that issue.

So exclude nodes that belong to ways from the autofix suggestion but not the entire check? 

> If, however the two nodes (in the same place) have different tags then there may be reasons to merge the tags. (eg. a crosswalk node on top of a non tagged node of a way) This may be what you are suggesting would be a new check?

I was just thinking this would be a different scenario within this check to investigate the nodes, aside from the autofix suggestion. 

>I'm actually not quite sure how this check can work very well since the default atlas generation process filters out all nodes that don't have tags so all the possible duplicate nodes with no tags will not be in the atlas files that we are scanning (unless we use the "keepAll" flag.

So exclude all nodes that don't have tags? (I would think not since there may be instances where "keepAll" might be used?)

**Comment by reichg** [comment]
based on discussion I think this idea should be dropped for now? Can we close this issue?

**Comment by Bentleysb** [comment]
Agreed, it appears this would be generally redundant.
